version: '3'
services:
    mongodb:
      image: mongo:3.2.4
      container_name: "mongodb"
      ports:
        - 27017:27017
      command: --smallfiles
    courses-search:
      image: acn/courses-search
      ports:
        - "9090:9090"
      links:
        - mongodb
      networks:
        - backend
      environment:
        - "spring.profiles.active=dev"
    courses-registration:
      image: acn/courses-registration
      ports:
        - "8080:8080"
      links:
        - mongodb
      networks:
        - backend
      environment:
        - "spring.profiles.active=dev"
    courses-view:
      image: acn/courses-registration
      ports:
        - "3000:3000"
      links:
        - courses-search
        - courses-registration
      networks:
        - backend
      environment:
        - "spring.profiles.active=dev"
networks:
  backend:






