spring:
  application:
    name: courses-view
  profiles:
    active: dev

---
spring:
  profiles: dev
  webflux:
    static-path-pattern: /content/**
  web:
    resources:
      static-location: classpath:/files/,classpath:/static-files
  mvc:
    static-path-pattern: /content/**
server:
  port: 3000
